// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMtfDsw2O77v492gWSgeXKg2fcUqYVP1g',
    appId: '1:559082766933:android:388c96c477adbe0d4f0adc',
    messagingSenderId: '559082766933',
    projectId: 'pawpawl',
    storageBucket: 'pawpawl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANHykw6hIXEMpGx8pOlKIsHY9QFrbR98o',
    appId: '1:559082766933:ios:3b8b9c98d51bc8f14f0adc',
    messagingSenderId: '559082766933',
    projectId: 'pawpawl',
    storageBucket: 'pawpawl.firebasestorage.app',
    androidClientId: '559082766933-d63tv2afeqptq2qmd52a36g3htp0qn2c.apps.googleusercontent.com',
    iosClientId: '559082766933-6t97j6u2v8kgosp8rbmj8jvlvc8r72au.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawpawl',
  );

}