-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.adoption_listings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  pet_name character varying NOT NULL,
  pet_type character varying NOT NULL,
  breed character varying,
  age character varying,
  gender character varying CHECK (gender::text = ANY (ARRAY['male'::character varying, 'female'::character varying, 'unknown'::character varying]::text[])),
  size character varying CHECK (size::text = ANY (ARRAY['small'::character varying, 'medium'::character varying, 'large'::character varying, 'xlarge'::character varying]::text[])),
  color character varying,
  description text NOT NULL,
  medical_info text,
  is_vaccinated boolean DEFAULT false,
  is_neutered boolean DEFAULT false,
  is_trained boolean DEFAULT false,
  good_with_kids boolean,
  good_with_pets boolean,
  image_urls ARRAY,
  location text,
  contact_phone character varying,
  contact_email character varying,
  adoption_fee numeric DEFAULT 0,
  status character varying DEFAULT 'available'::character varying CHECK (status::text = ANY (ARRAY['available'::character varying, 'pending'::character varying, 'adopted'::character varying, 'removed'::character varying]::text[])),
  user_name character varying,
  user_avatar text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pet_id uuid,
  CONSTRAINT adoption_listings_pkey PRIMARY KEY (id),
  CONSTRAINT adoption_listings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT adoption_listings_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id)
);
CREATE TABLE public.booking_completion_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  summary text NOT NULL,
  activities_performed ARRAY,
  feeding_notes text,
  bathroom_notes text,
  behavior_notes text,
  health_observations text,
  photo_urls ARRAY,
  video_urls ARRAY,
  actual_duration_minutes integer,
  distance_walked_km numeric,
  submitted_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  owner_acknowledged_at timestamp with time zone,
  CONSTRAINT booking_completion_reports_pkey PRIMARY KEY (id),
  CONSTRAINT booking_completion_reports_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.service_bookings(id)
);
CREATE TABLE public.booking_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'PKR'::character varying,
  payment_type character varying NOT NULL CHECK (payment_type::text = ANY (ARRAY['deposit'::character varying, 'final'::character varying, 'refund'::character varying, 'tip'::character varying]::text[])),
  payment_method character varying CHECK (payment_method::text = ANY (ARRAY['card'::character varying, 'wallet'::character varying, 'bank_transfer'::character varying, 'cash'::character varying, 'jazzcash'::character varying, 'easypaisa'::character varying]::text[])),
  transaction_id character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying, 'refunded'::character varying, 'held'::character varying]::text[])),
  escrow_held_at timestamp with time zone,
  escrow_released_at timestamp with time zone,
  payout_status character varying DEFAULT 'pending'::character varying CHECK (payout_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  payout_amount numeric,
  platform_fee numeric,
  payout_transaction_id character varying,
  payout_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT booking_payments_pkey PRIMARY KEY (id),
  CONSTRAINT booking_payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.service_bookings(id)
);
CREATE TABLE public.booking_tracking (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  accuracy_meters numeric,
  activity_type character varying CHECK (activity_type::text = ANY (ARRAY['started'::character varying, 'walking'::character varying, 'stopped'::character varying, 'arrived'::character varying, 'feeding'::character varying, 'playing'::character varying, 'resting'::character varying, 'completed'::character varying]::text[])),
  note text,
  recorded_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT booking_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT booking_tracking_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.service_bookings(id)
);
CREATE TABLE public.caregiver_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  caregiver_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  is_available boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT caregiver_availability_pkey PRIMARY KEY (id),
  CONSTRAINT caregiver_availability_caregiver_id_fkey FOREIGN KEY (caregiver_id) REFERENCES public.caregiver_profiles(id)
);
CREATE TABLE public.caregiver_blocked_dates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  caregiver_id uuid NOT NULL,
  blocked_date date NOT NULL,
  reason character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT caregiver_blocked_dates_pkey PRIMARY KEY (id),
  CONSTRAINT caregiver_blocked_dates_caregiver_id_fkey FOREIGN KEY (caregiver_id) REFERENCES public.caregiver_profiles(id)
);
CREATE TABLE public.caregiver_gallery (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  caregiver_id uuid NOT NULL,
  image_url text NOT NULL,
  caption text,
  is_primary boolean DEFAULT false,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT caregiver_gallery_pkey PRIMARY KEY (id),
  CONSTRAINT caregiver_gallery_caregiver_id_fkey FOREIGN KEY (caregiver_id) REFERENCES public.caregiver_profiles(id)
);
CREATE TABLE public.caregiver_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  bio text,
  years_of_experience integer DEFAULT 0,
  headline character varying,
  address text,
  city character varying,
  state character varying,
  postal_code character varying,
  country character varying DEFAULT 'Pakistan'::character varying,
  latitude numeric,
  longitude numeric,
  service_radius_km integer DEFAULT 10,
  is_verified boolean DEFAULT false,
  verification_date timestamp with time zone,
  background_check_status character varying DEFAULT 'pending'::character varying CHECK (background_check_status::text = ANY (ARRAY['pending'::character varying, 'in_progress'::character varying, 'approved'::character varying, 'rejected'::character varying, 'expired'::character varying]::text[])),
  background_check_date timestamp with time zone,
  background_check_expiry timestamp with time zone,
  id_verified boolean DEFAULT false,
  id_document_url text,
  certifications ARRAY,
  pet_first_aid_certified boolean DEFAULT false,
  insurance_verified boolean DEFAULT false,
  insurance_policy_number character varying,
  insurance_expiry timestamp with time zone,
  accepted_pet_types ARRAY DEFAULT ARRAY['dog'::text, 'cat'::text],
  accepted_pet_sizes ARRAY DEFAULT ARRAY['small'::text, 'medium'::text, 'large'::text],
  max_pets_at_once integer DEFAULT 3,
  has_fenced_yard boolean DEFAULT false,
  has_own_transport boolean DEFAULT false,
  smoke_free_home boolean DEFAULT true,
  has_children boolean DEFAULT false,
  has_other_pets boolean DEFAULT false,
  other_pets_description text,
  average_rating numeric DEFAULT 0,
  total_reviews integer DEFAULT 0,
  total_bookings integer DEFAULT 0,
  completion_rate numeric DEFAULT 100,
  response_time_hours integer DEFAULT 24,
  is_active boolean DEFAULT true,
  is_accepting_bookings boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT caregiver_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT caregiver_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.caregiver_service_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  display_name character varying NOT NULL,
  description text,
  base_hourly_rate numeric DEFAULT 0,
  icon_name character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT caregiver_service_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.caregiver_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  caregiver_id uuid NOT NULL,
  service_type_id uuid NOT NULL,
  rate_type character varying DEFAULT 'hourly'::character varying CHECK (rate_type::text = ANY (ARRAY['hourly'::character varying, 'per_visit'::character varying, 'daily'::character varying, 'per_walk'::character varying]::text[])),
  rate_amount numeric NOT NULL,
  currency character varying DEFAULT 'PKR'::character varying,
  description text,
  duration_minutes integer,
  includes ARRAY,
  additional_pet_rate numeric DEFAULT 0,
  is_available boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT caregiver_services_pkey PRIMARY KEY (id),
  CONSTRAINT caregiver_services_caregiver_id_fkey FOREIGN KEY (caregiver_id) REFERENCES public.caregiver_profiles(id),
  CONSTRAINT caregiver_services_service_type_id_fkey FOREIGN KEY (service_type_id) REFERENCES public.caregiver_service_types(id)
);
CREATE TABLE public.cart_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cart_items_pkey PRIMARY KEY (id),
  CONSTRAINT cart_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT cart_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.chats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  pet_owner_id uuid NOT NULL,
  vet_id uuid NOT NULL,
  last_message text,
  last_message_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pet_id uuid,
  unread_count_owner integer DEFAULT 0,
  unread_count_vet integer DEFAULT 0,
  booking_id uuid,
  chat_type character varying DEFAULT 'general'::character varying CHECK (chat_type::text = ANY (ARRAY['general'::character varying, 'vet_consultation'::character varying, 'booking_inquiry'::character varying, 'active_booking'::character varying]::text[])),
  appointment_id uuid,
  CONSTRAINT chats_pkey PRIMARY KEY (id),
  CONSTRAINT chats_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.service_bookings(id),
  CONSTRAINT chats_pet_owner_id_fkey FOREIGN KEY (pet_owner_id) REFERENCES public.users(id),
  CONSTRAINT chats_vet_id_fkey FOREIGN KEY (vet_id) REFERENCES public.users(id),
  CONSTRAINT chats_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT chats_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.vet_appointments(id)
);
CREATE TABLE public.comments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  parent_comment_id uuid,
  content text NOT NULL,
  user_name character varying,
  user_avatar text,
  likes_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT comments_pkey PRIMARY KEY (id),
  CONSTRAINT comments_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.posts(id),
  CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT comments_parent_comment_id_fkey FOREIGN KEY (parent_comment_id) REFERENCES public.comments(id)
);
CREATE TABLE public.event_rsvps (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_id uuid NOT NULL,
  user_id uuid NOT NULL,
  status character varying DEFAULT 'going'::character varying CHECK (status::text = ANY (ARRAY['going'::character varying, 'interested'::character varying, 'waitlisted'::character varying]::text[])),
  user_name character varying,
  user_avatar text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT event_rsvps_pkey PRIMARY KEY (id),
  CONSTRAINT event_rsvps_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_rsvps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organizer_id uuid NOT NULL,
  title character varying NOT NULL,
  description text NOT NULL,
  event_type character varying DEFAULT 'meetup'::character varying CHECK (event_type::text = ANY (ARRAY['meetup'::character varying, 'adoption_drive'::character varying, 'training'::character varying, 'competition'::character varying, 'charity'::character varying, 'other'::character varying]::text[])),
  image_url text,
  location text,
  location_lat numeric,
  location_lng numeric,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  max_attendees integer,
  is_pet_friendly boolean DEFAULT true,
  pet_types_allowed ARRAY,
  status character varying DEFAULT 'upcoming'::character varying CHECK (status::text = ANY (ARRAY['upcoming'::character varying, 'ongoing'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  organizer_name character varying,
  organizer_avatar text,
  rsvp_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_organizer_id_fkey FOREIGN KEY (organizer_id) REFERENCES public.users(id)
);
CREATE TABLE public.health_journals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  pet_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  date date NOT NULL,
  weight numeric,
  weight_unit character varying CHECK (weight_unit::text = ANY (ARRAY['kg'::character varying, 'lbs'::character varying]::text[])),
  activity_level character varying CHECK (activity_level::text = ANY (ARRAY['low'::character varying, 'moderate'::character varying, 'high'::character varying]::text[])),
  energy_level character varying CHECK (energy_level::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying]::text[])),
  mood character varying CHECK (mood::text = ANY (ARRAY['happy'::character varying, 'sad'::character varying, 'anxious'::character varying, 'aggressive'::character varying, 'calm'::character varying]::text[])),
  appetite character varying CHECK (appetite::text = ANY (ARRAY['good'::character varying, 'poor'::character varying, 'normal'::character varying]::text[])),
  symptoms ARRAY,
  medications_taken ARRAY,
  vet_visit boolean DEFAULT false,
  vet_visit_reason text,
  vet_notes text,
  general_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT health_journals_pkey PRIMARY KEY (id),
  CONSTRAINT health_journals_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT health_journals_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.health_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  pet_id uuid NOT NULL,
  owner_id uuid NOT NULL,
  is_vaccinated boolean DEFAULT false,
  vaccination_date date,
  vaccination_details text,
  medical_conditions ARRAY,
  allergies ARRAY,
  medications ARRAY,
  vet_name character varying,
  vet_clinic character varying,
  vet_phone character varying,
  vet_address text,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  insurance_provider character varying,
  insurance_policy_number character varying,
  additional_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT health_records_pkey PRIMARY KEY (id),
  CONSTRAINT health_records_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id),
  CONSTRAINT health_records_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.likes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  target_id uuid NOT NULL,
  target_type character varying NOT NULL CHECK (target_type::text = ANY (ARRAY['post'::character varying, 'comment'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT likes_pkey PRIMARY KEY (id),
  CONSTRAINT likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.lost_found_posts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['lost'::character varying, 'found'::character varying]::text[])),
  pet_name character varying,
  pet_type character varying,
  breed character varying,
  color character varying,
  description text NOT NULL,
  image_urls ARRAY,
  last_seen_location text,
  last_seen_lat numeric,
  last_seen_lng numeric,
  urgency character varying DEFAULT 'medium'::character varying CHECK (urgency::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  contact_phone character varying,
  contact_email character varying,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'resolved'::character varying, 'expired'::character varying]::text[])),
  user_name character varying,
  user_avatar text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lost_found_posts_pkey PRIMARY KEY (id),
  CONSTRAINT lost_found_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  chat_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text NOT NULL,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_chat_id_fkey FOREIGN KEY (chat_id) REFERENCES public.chats(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id)
);
CREATE TABLE public.order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  product_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  total_price numeric NOT NULL CHECK (total_price >= 0::numeric),
  seller_status character varying DEFAULT 'pending'::character varying CHECK (seller_status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'cancelled'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_items_pkey PRIMARY KEY (id),
  CONSTRAINT order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT order_items_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.users(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  buyer_id uuid NOT NULL,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'processing'::character varying, 'shipped'::character varying, 'delivered'::character varying, 'cancelled'::character varying, 'refunded'::character varying]::text[])),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  currency character varying DEFAULT 'PKR'::character varying,
  shipping_address text NOT NULL,
  shipping_city character varying,
  shipping_phone character varying,
  payment_method character varying DEFAULT 'cash_on_delivery'::character varying,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'paid'::character varying, 'failed'::character varying, 'refunded'::character varying]::text[])),
  tracking_number character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.users(id)
);
CREATE TABLE public.password_reset_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  used boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT password_reset_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.pets (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  owner_id uuid NOT NULL,
  name character varying NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['dog'::character varying, 'cat'::character varying]::text[])),
  breed character varying NOT NULL,
  age integer NOT NULL,
  age_unit character varying NOT NULL CHECK (age_unit::text = ANY (ARRAY['months'::character varying, 'years'::character varying]::text[])),
  gender character varying NOT NULL CHECK (gender::text = ANY (ARRAY['male'::character varying, 'female'::character varying]::text[])),
  color character varying NOT NULL,
  weight numeric NOT NULL,
  weight_unit character varying NOT NULL CHECK (weight_unit::text = ANY (ARRAY['kg'::character varying, 'lbs'::character varying]::text[])),
  image_url text,
  image_local_path text,
  image_urls ARRAY,
  is_verified boolean DEFAULT false,
  verification_confidence numeric,
  verified_breed character varying,
  bio text,
  is_adopted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pets_pkey PRIMARY KEY (id),
  CONSTRAINT pets_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.users(id)
);
CREATE TABLE public.posts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  content text NOT NULL,
  user_name character varying,
  user_avatar text,
  image_urls ARRAY,
  likes_count integer DEFAULT 0,
  comments_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  category text DEFAULT 'general'::text,
  CONSTRAINT posts_pkey PRIMARY KEY (id),
  CONSTRAINT posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.product_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL UNIQUE,
  description text,
  icon_url text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  user_id uuid NOT NULL,
  order_item_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT product_reviews_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT product_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT product_reviews_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES public.order_items(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  seller_id uuid NOT NULL,
  category_id uuid,
  name character varying NOT NULL,
  description text NOT NULL,
  price numeric NOT NULL CHECK (price >= 0::numeric),
  currency character varying DEFAULT 'PKR'::character varying,
  stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  images ARRAY,
  breed_compatibility ARRAY,
  pet_type character varying CHECK (pet_type::text = ANY (ARRAY['dog'::character varying, 'cat'::character varying, 'both'::character varying, 'other'::character varying]::text[])),
  weight_grams integer,
  is_active boolean DEFAULT true,
  rating numeric DEFAULT 0.00 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  total_reviews integer DEFAULT 0,
  total_sold integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.users(id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.product_categories(id)
);
CREATE TABLE public.refresh_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  token character varying NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  revoked boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT refresh_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.service_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_number character varying NOT NULL UNIQUE,
  pet_owner_id uuid NOT NULL,
  caregiver_id uuid NOT NULL,
  service_id uuid NOT NULL,
  pet_ids ARRAY NOT NULL,
  start_datetime timestamp with time zone NOT NULL,
  end_datetime timestamp with time zone NOT NULL,
  service_location_type character varying DEFAULT 'owner_home'::character varying CHECK (service_location_type::text = ANY (ARRAY['owner_home'::character varying, 'caregiver_home'::character varying, 'pickup_location'::character varying, 'outdoor'::character varying]::text[])),
  service_address text,
  service_latitude numeric,
  service_longitude numeric,
  special_instructions text,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  base_amount numeric NOT NULL,
  additional_pets_fee numeric DEFAULT 0,
  service_fee numeric DEFAULT 0,
  discount_amount numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  currency character varying DEFAULT 'PKR'::character varying,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying, 'cancelled_owner'::character varying, 'cancelled_caregiver'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'disputed'::character varying]::text[])),
  requested_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  responded_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT service_bookings_pet_owner_id_fkey FOREIGN KEY (pet_owner_id) REFERENCES public.users(id),
  CONSTRAINT service_bookings_caregiver_id_fkey FOREIGN KEY (caregiver_id) REFERENCES public.caregiver_profiles(id),
  CONSTRAINT service_bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.caregiver_services(id)
);
CREATE TABLE public.service_incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  incident_number character varying NOT NULL UNIQUE,
  booking_id uuid NOT NULL,
  reported_by uuid NOT NULL,
  incident_type character varying NOT NULL CHECK (incident_type::text = ANY (ARRAY['injury_pet'::character varying, 'injury_caregiver'::character varying, 'pet_escape'::character varying, 'property_damage'::character varying, 'behavioral_issue'::character varying, 'medical_emergency'::character varying, 'service_quality'::character varying, 'safety_concern'::character varying, 'other'::character varying]::text[])),
  severity character varying NOT NULL CHECK (severity::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'critical'::character varying]::text[])),
  description text NOT NULL,
  occurred_at timestamp with time zone NOT NULL,
  location_description text,
  photo_urls ARRAY,
  video_urls ARRAY,
  status character varying DEFAULT 'reported'::character varying CHECK (status::text = ANY (ARRAY['reported'::character varying, 'under_review'::character varying, 'investigating'::character varying, 'resolved'::character varying, 'closed'::character varying, 'escalated'::character varying]::text[])),
  resolution_notes text,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  insurance_claim_filed boolean DEFAULT false,
  insurance_claim_number character varying,
  insurance_claim_status character varying,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_incidents_pkey PRIMARY KEY (id),
  CONSTRAINT service_incidents_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.service_bookings(id),
  CONSTRAINT service_incidents_reported_by_fkey FOREIGN KEY (reported_by) REFERENCES public.users(id),
  CONSTRAINT service_incidents_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.users(id)
);
CREATE TABLE public.service_reviews (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL UNIQUE,
  owner_rating integer CHECK (owner_rating >= 1 AND owner_rating <= 5),
  owner_review text,
  owner_review_at timestamp with time zone,
  communication_rating integer CHECK (communication_rating >= 1 AND communication_rating <= 5),
  reliability_rating integer CHECK (reliability_rating >= 1 AND reliability_rating <= 5),
  care_quality_rating integer CHECK (care_quality_rating >= 1 AND care_quality_rating <= 5),
  caregiver_rating integer CHECK (caregiver_rating >= 1 AND caregiver_rating <= 5),
  caregiver_review text,
  caregiver_review_at timestamp with time zone,
  pet_behavior_rating integer CHECK (pet_behavior_rating >= 1 AND pet_behavior_rating <= 5),
  is_public boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT service_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT service_reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.service_bookings(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  role character varying NOT NULL CHECK (role::text = ANY (ARRAY['pet_owner'::character varying, 'vet'::character varying, 'seller'::character varying, 'caregiver'::character varying, 'admin'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL UNIQUE,
  password_hash character varying DEFAULT ''::character varying,
  display_name character varying,
  account_type character varying DEFAULT 'pet_owner'::character varying,
  avatar_url text,
  is_active boolean DEFAULT true,
  email_verified boolean DEFAULT false,
  google_id character varying UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_role character varying DEFAULT 'petowner'::character varying CHECK (user_role::text = ANY (ARRAY['petowner'::character varying, 'vet'::character varying, 'caregiver'::character varying]::text[])),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.vet_appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_number character varying UNIQUE,
  pet_owner_id uuid NOT NULL,
  vet_user_id uuid NOT NULL,
  pet_id uuid NOT NULL,
  reason text NOT NULL,
  symptoms text,
  owner_notes text,
  appointment_datetime timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 30 CHECK (duration_minutes > 0 AND duration_minutes <= 240),
  meeting_type character varying NOT NULL DEFAULT 'in_person'::character varying CHECK (meeting_type::text = ANY (ARRAY['in_person'::character varying, 'video'::character varying, 'chat'::character varying]::text[])),
  clinic_address text,
  meeting_link text,
  fee_amount numeric NOT NULL DEFAULT 0,
  currency character varying NOT NULL DEFAULT 'PKR'::character varying,
  status character varying NOT NULL DEFAULT 'requested'::character varying CHECK (status::text = ANY (ARRAY['requested'::character varying, 'confirmed'::character varying, 'declined'::character varying, 'cancelled_owner'::character varying, 'cancelled_vet'::character varying, 'completed'::character varying]::text[])),
  response_note text,
  responded_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  completed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT vet_appointments_pkey PRIMARY KEY (id),
  CONSTRAINT vet_appointments_pet_owner_id_fkey FOREIGN KEY (pet_owner_id) REFERENCES public.users(id),
  CONSTRAINT vet_appointments_vet_user_id_fkey FOREIGN KEY (vet_user_id) REFERENCES public.users(id),
  CONSTRAINT vet_appointments_pet_id_fkey FOREIGN KEY (pet_id) REFERENCES public.pets(id)
);
CREATE TABLE public.vet_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  full_name character varying NOT NULL,
  degree character varying NOT NULL,
  license_number character varying,
  specialization ARRAY,
  experience integer NOT NULL DEFAULT 0,
  clinic_name character varying,
  clinic_address text,
  city character varying,
  state character varying,
  zip_code character varying,
  phone character varying NOT NULL,
  consultation_fee numeric NOT NULL DEFAULT 0.00,
  currency character varying DEFAULT 'USD'::character varying,
  bio text,
  profile_photo_url text,
  availability_hours text,
  rating numeric DEFAULT 0.00 CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  total_reviews integer DEFAULT 0,
  is_verified boolean DEFAULT false,
  is_available boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vet_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT vet_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.vet_reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  vet_id uuid NOT NULL,
  user_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT vet_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT vet_reviews_vet_id_fkey FOREIGN KEY (vet_id) REFERENCES public.users(id),
  CONSTRAINT vet_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);